# Generated by Django 2.0.7 on 2018-07-19 16:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('semiRest', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
            ],
        ),
    ]
